### ISSUE TITLE
Image Block component - different layout when reversed

### ISSUE THREAD

**Issue by wwitekk** [Alchemy-se/Vattenfall-One-Brand-Design-System#100]
Hi

Image Block component when reversed displays text differently (2 lines instead of 1 in header). Please find image below.

![image](https://user-images.githubusercontent.com/4947059/59496043-ea5e6380-8e90-11e9-9c57-1db048091be7.png)

Another issue is that in the example (https://digitaldesign.vattenfall.com/css/image-block) you are using rounded png image. Do you really want us to use rounded png image in here?

Regards 

Witold

**Comment by alchemychrishall** [comment]
Hi Witold!

Thanks for letting us know. The padding has been standardised, and so the text will now be displayed in the same way.

Yes, the rounded image is correct there.

Regards,

Chris

**Comment by wwitekk** [comment]
Hi Chris,

Thank you very much for your feedback and quick bug fix.

Just one more regarding rounded images. Still not understand why you do not want to add little bit of css like:

`.vf-image-block {
  &__media {
       img {
      height: 250px;
      width: 250px;
      border-radius: 50%;
      object-fit: cover;
    }
  }`

I am using the component inside cms - that will be impossible to explain to editors why and how to prepare rounded png. They want to download an image from Frontify media library and upload it into cms with no additional edition.

Witold
