### ISSUE TITLE
IE11: Input tooltip icon missing

### ISSUE THREAD

**Issue by MikaelPorttila** [Alchemy-se/Vattenfall-One-Brand-Design-System#115]
Browser: IE11
OS: Win 10 Pro

Missing input tooltip icon in IE11
https://digitaldesign.vattenfall.com/css/input#with-tooltip

**Comment by alchemychrishall** [comment]
Hi Mikael!

Thanks for letting us know. The icons should now appear correctly.

Regards,

Chris
