### ISSUE TITLE
No <p> tag allowed in 2-columns text component?

### ISSUE THREAD

**Issue by wwitekk** [Alchemy-se/Vattenfall-One-Brand-Design-System#98]
Hi

Under url: https://digitaldesign.vattenfall.com/investors.html there is text formatted in 2 columns: 
![image](https://user-images.githubusercontent.com/4947059/59179319-f0d39f00-8b61-11e9-80b1-2e5cdf47f9e0.png)

Font size in there is smaller than other content on the page and no <p> tags inside. 
What styles should be used in there if I need to use paragraphs?

Witold

**Comment by alchemychrishall** [comment]
Hi!

To change the font size, please use either a class or a mixin found here: https://digitaldesign.vattenfall.com/css/text .

In your case, perhaps `typo-paragraph-primary()` or `typo-paragraph-secondary()` would be applicable.

Regards,

Chris

**Comment by wwitekk** [comment]
Thank you for help.
